version: 2

models:
  - name: weather_data_cleansed
    description: Cleansed table which contains weather data
    columns:
      
      - name: id
        description: Primary key 
        tests:
          - unique:
              where: "run_id = '{{ var(\"run_id\") }}'"
          - not_null:
              where: "run_id = '{{ var(\"run_id\") }}'"
          - relationships:
              to: source('dev', 'raw_weather_data')
              field: id
        
      - name: city
        description: Name of city data come from
        tests:
          - not_null:
              where: "run_id = '{{ var(\"run_id\") }}'"
      
      - name: temperature
        description: Temperature of city
        tests:
          - range_values:   # custom test
              where: "run_id = '{{ var(\"run_id\") }}'"

      - name: wind_direction
        description: Wind direction in compass values
        tests:
          - accepted_values:
              values: ['N','NNE','NE','ENE','E','ESE','SE','SSE',
                       'S','SSW','SW','WSW','W','WNW','NW','NNW']
              where: "run_id = '{{ var(\"run_id\") }}'"



  - name: control_table
    description: Tracks pipeline runs
    columns:
      - name: id
        description: Foreign key from raw_weather_data
        tests:
          - unique
          - not_null
          - relationships:
              to: source('dev', 'raw_weather_data')
              field: id
                      
