version: 2

sources:
  - name: dev
    database: db
    tables:
      - name: raw_weather_data
        columns:
          - name: id
          - name: city
          - name: country
          - name: temperature
          - name: weather_description
          - name: wind_speed
          - name: wind_direction
          - name: humidity
          - name: visibility
          - name: time
          - name: inserted_at
          - name: utc_offset
